global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring"
    metrics_path: "/actuator/prometheus"
    basic_auth:
      username: "monitor"
      password: "monitor-pass-CHANGE-ME"
    static_configs:
      - targets: ["host.docker.internal:8080"]